### ISSUE TITLE
Sort Cases?

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#136]
On the [Case Index page](http://rosie.unl.edu/earlywashingtondc/cases/all), we said we would offer "other ways to sort through these records at a later date." I don't know if this is still in the cards or not.

**Comment by jduss4** [comment]
@kacinash has asked me to add the latest document's date to the cases for searching.  I think that I will need to wait until after we've changed from XSLT posting to Ruby posting so that the case can gather all the documents and compare at the same time.  By using the date field, we should be able to use the same code as the documents to sort alphabetically or by date

**Comment by jduss4** [comment]
PR merged:  https://github.com/CDRH/earlywashingtondc/pull/227
closing
