### ISSUE TITLE
per.000790 in solr not the same as per.000790 in rdf

### ISSUE THREAD

**Issue by jduss4** [CDRH/earlywashingtondc#173]
http://earlywashingtondc.org/people/per.000790  = Daniel Valentine
http://earlywashingtondc.org/people/network/per.000790 = Mary Riley

**Comment by lweakly** [comment]
This was a list of witnesses. I put one person on twice (Priscilla Newman) and skipped one person (Catharine Wheat). 

In the rdf it was:
per.000788 Priscilla Newman
per.000789 Priscilla Newman
per.000790 Mary Riley
per.000791 Daniel Valentine
per.000792 William Wheat

It is now:
per.000788 Priscilla Newman
per.000789 Mary Riley
per.000790 Daniel Valentine
per.000791 Catharine Wheat
per.000792 William Wheat

The relationships should be OK, since they were all witnesses for the same defendant Gerard Greenfield (per.000775).

We will want to look at this once it is live to make sure everything is OK.
