### ISSUE TITLE
How to encode <pb> with no images?

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#200]
How do I encode a page break for an instance where there is no page image associated with it? 

This document is missing a page, but we have a transcription for the missing page. I tried removed the `facs` - `<pb xml:id="p012"/>` and the `xml:id` - `<pb/>` but no matter what, it still shows as a broken image. 

http://earlywashingtondc.org/doc/oscys.mdcase.0007.003 - see page 11

There will be instances in the future where we will have documents without images. I will need to know how to encode the necessary page breaks without a broken image showing up.

**Comment by jduss4** [comment]
This is happening in the data script's `cdrh.xsl` file.  It's constructing a variable named `$figure_id` which can be blank if there are no `@facs` or `@xml:id` attrs on it, and then that is plugged into an anchor tag.  @karindalziel do you think I should override this for OSCYS?  Or can I make it so that no span / anchors are created if `$figure_id` is empty?

**Comment by jduss4** [comment]
@kacinash leaving the `<pb>`s blank is perfect, hopefully the pull request above will fix this for you
