### ISSUE TITLE
Search sorts keep changing

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#204]
If I search for Prince George's County, Md., [the results are sorted alphabetically](http://earlywashingtondc.org/search?qfield=places&qtext=Prince+George%27s+County+%28Md.%29) by default. But when I click on [page two](http://earlywashingtondc.org/search?page=2&qfield=places&qtext=Prince+George%27s+County+%28Md.%29&sort=score), the sort switches to relevance, and I have to click alphabetical again in order to maintain the same search results. What do we need to do to keep the search sorting consistent across all the pages?

**Comment by jduss4** [comment]
Apparently OSCYS was made before the solr_helpers gem, which has some pagination and sorting stuff. Rather than debugging OSCYS's code, I'm going to try to plug in the gem and remove any of the older code.  This will require some testing to make sure that everything is good to go, but hopefully it will improve the pagination and sorting

**Comment by jduss4** [comment]
Fixed with this: https://github.com/CDRH/earlywashingtondc/pull/205
